# Vectors and Matrices operation

---
This notebook highlights the principal operation that we can compute in python on vectors and matrices, by using different libriry (e.g. numpy). Then, we will focus on the definition of different type of matrices and in the last part we will compare the different computational by using or not using the loop to compute some operation with vectors (or matrices).


In [1]:
import numpy as np

## Basic operation with vectors

### Create a vector using *np.array*


In [2]:
A = np.array([3., 5., 6.])
print('Vector created usigng np.array:',A)

Vector created usigng np.array: [3. 5. 6.]


### Check the size of vector


---
**NB**: There is no difference with array between row vectors and column vectors


In [3]:
print('Vector "A" has the following size:', A.size)

Vector "A" has the following size: 3


### Sum all the element of a vector

In [4]:
print('Sum of element computed by adding each element:', A[0] + A[1] + A[2])
print('Sum of element computed by using function np.sum:', np.sum(A))


Sum of element computed by adding each element: 14.0
Sum of element computed by using function np.sum: 14.0


### Check for minimum value and index on minimum value of a vactor

In [5]:
print('Min element of a vector using function np.min:', np.min(A))

Min element of a vector using function np.min: 3.0


In [6]:
print('Index of min value into a vector using function np.argmin:', np.argmin(A))
print('Min element of a vector by discovering the related index using function np.argmin: ', A[np.argmin(A)])

Index of min value into a vector using function np.argmin: 0
Min element of a vector by discovering the related index using function np.argmin:  3.0


### Check for maximum value and index on maximum value of a vactor

In [7]:
print('Max element of a vector using function np.max:', np.max(A))

Max element of a vector using function np.max: 6.0


In [8]:
print('Index of max value into a vector using function np.argmax:', np.argmax(A))
print('Max element of a vector by discovering the related index using function np.argmax: ', A[np.argmax(A)])

Index of max value into a vector using function np.argmax: 2
Max element of a vector by discovering the related index using function np.argmax:  6.0


### Creating a vector using *np.linspace*
**NB**: linspace allows you to specify the *number* of steps
> np.linspace(start, stop, num, …), where num is the number of values to generate.




In [9]:
x = np.linspace(-50,-1,5) # Create a vector of 5 element in range (-50, -1)
print('The vector x has the following elements:, ', x)
print('The object type of x is:', type(x))
print('The size of x is:', np.size(x))

The vector x has the following elements:,  [-50.   -37.75 -25.5  -13.25  -1.  ]
The object type of x is: <class 'numpy.ndarray'>
The size of x is: 5


### Creating a vector using *np.arange*
**NB**: arange you to specify the *size* of the steps
> np.arange(start, stop, step, …), where step is the spacing between values.

In [10]:
y = np.arange(1,10,2) # Create a vector with values in range (1,10) with an increment of 2
print('The vector y has the following elements:, ', y)
print('The object type of y is:', type(y))
print('The size of y is:', np.size(y))

The vector y has the following elements:,  [1 3 5 7 9]
The object type of y is: <class 'numpy.ndarray'>
The size of y is: 5


#### Change the order of all the elements in a vector

In [11]:
y = np.arange(10)
print('Vector y: {}'.format(y))
print('--- change the order ---')
print('Vector y: {}'.format(y[::-1]))

Vector y: [0 1 2 3 4 5 6 7 8 9]
--- change the order ---
Vector y: [9 8 7 6 5 4 3 2 1 0]


### Boolean operation with vectors

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print('Check if two vectors are equals (element by element): ', a == b)

Check if two vectors are equals (element by element):  [False  True False  True]


In [13]:
print('Check if one vector is greater than another one (element by element): ', a > b)

Check if one vector is greater than another one (element by element):  [False False  True False]


### Math operation with vectors

In [14]:
print('Computing the sin(x) of each element of a given vector "a"')
print('a: {}'.format(a))
print('sin(a): {}'.format(np.sin(a)))

Computing the sin(x) of each element of a given vector "a"
a: [1 2 3 4]
sin(a): [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [15]:
print('Computing the sin(x) of a specific element of a given vector "a"')
print('a[0]: {}'.format(a[0]))
print('sin(a[0]): {}'.format(np.sin(a[0])))

Computing the sin(x) of a specific element of a given vector "a"
a[0]: 1
sin(a[0]): 0.8414709848078965


## Basic operation with matrices

### Create a matrix using *np.array*

In [16]:
A=np.array([[  3.,   5.,   7.],
           [  8.,   9.,  10.],
           [  2.,   3.,   5.]])
print('Matrix created usigng np.array:\n',A)

Matrix created usigng np.array:
 [[ 3.  5.  7.]
 [ 8.  9. 10.]
 [ 2.  3.  5.]]


### Check the object type

In [17]:
print('The object type of A is:', type(A))

The object type of A is: <class 'numpy.ndarray'>


### Check the dimension and size of matrix

---


*   ***ndim*** tell us how many dimension the matrix has (2D, 3D, ...)
*   ***shape*** tell us the number of element in each dimension. In case of 2D dimension, it will define the number of rows and columns, respectivelly




In [18]:
print('The matrix A has the following dimension:', A.ndim)

The matrix A has the following dimension: 2


In [19]:
print('The matrix A has the following number of rows and columns (nrow,ncol):', A.shape)

The matrix A has the following number of rows and columns (nrow,ncol): (3, 3)


### Select a specific element in position (i,j)

In [20]:
print('Matrix element in position (0,0):', A[0,0])
print('Matrix element in position (1,0):', A[1,0])
print('Matrix element in position (2,0):', A[2,0])

Matrix element in position (0,0): 3.0
Matrix element in position (1,0): 8.0
Matrix element in position (2,0): 2.0


### Select a specific column of a matrix (i,0)

In [21]:
print('Matrix column in position (i,0):', A[:,0])

Matrix column in position (i,0): [3. 8. 2.]


### Select a specific row of a matrix (0,j)

In [22]:
print('Matrix row in position (0,j):', A[0,:])

Matrix row in position (0,j): [3. 5. 7.]


### Select a specific subset of a matrix

In [23]:
print('Submatrix of A, with i = 1,2, j= 1,2\n', A[1:3,1:3])

Submatrix of A, with i = 1,2, j= 1,2
 [[ 9. 10.]
 [ 3.  5.]]


## Create different type of matrices

### Empty matrix of a specific size
Create an empty matrix (or vector) with a specific size

In [24]:
print('Empty vector of size (3,4):\n\n', np.empty((3,4)))
print('\nEmpty vector of size (5,2):\n\n', np.empty((5,2)))

Empty vector of size (3,4):

 [[5.02469942e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]

Empty vector of size (5,2):

 [[5.02432428e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [1.29061927e+248 1.04073706e-071]
 [1.38058759e-047 4.22180985e-090]
 [4.04509458e-057 2.59475293e-029]]


In [25]:
C=np.empty((3,5))
print(C)

[[5.02432416e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
  1.03977794e-312]
 [1.50008929e+248 4.31174539e-096 9.80058441e+252 1.23971686e+224
  1.05206188e-153]
 [9.03292329e+271 9.08366793e+223 1.06244660e-153 3.44981369e+175
  6.32404027e-322]]


### Random matrix with uniform distribution
Create a matrix with 3 rows and 4 columns with random values between 0 and 10

In [26]:
A = np.random.rand(3,4)*10
print('The matrix A has the following element:\n',A)

The matrix A has the following element:
 [[8.34432698 0.30145555 5.8128625  8.69533104]
 [0.82027995 8.2105749  9.15368808 8.35554003]
 [5.61072703 5.18672569 8.61481303 9.69410743]]


### Square matrix with integer element
Create a square matrix with 3 rows and 3 columns with integer values between 0 and 10

In [27]:
A = np.random.randint(10,size=(3,3))
print('The matrix A has the following element:\n',A)

The matrix A has the following element:
 [[0 8 2]
 [8 8 0]
 [0 7 5]]


### Compute the Lower and Upper Triangular Matrix of a given matrix

In [28]:
U=np.triu(A)   # Compute the upper triangular part of A
print('The object type of U is:', type(U))
print('The Upper Triangular part of A is:\n', U)

L=np.tril(A)   # Compute the lower triangular part of A
print('\nThe object type of L is:', type(L))
print('The Lower Triangular part of A is:\n', L)

The object type of U is: <class 'numpy.ndarray'>
The Upper Triangular part of A is:
 [[0 8 2]
 [0 8 0]
 [0 0 5]]

The object type of L is: <class 'numpy.ndarray'>
The Lower Triangular part of A is:
 [[0 0 0]
 [8 8 0]
 [0 7 5]]


### Create the *null* matrix

In [29]:
O = np.zeros((3,3))
print('The object type of O is:', type(O))
print('Null matrix of size (3,3):\n',O)

The object type of O is: <class 'numpy.ndarray'>
Null matrix of size (3,3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Create the *Identity* matrix

In [30]:
I = np.eye(3)
print('The object type of I is:', type(I))
print('Identity matrix of size (3,3):\n',I)

The object type of I is: <class 'numpy.ndarray'>
Identity matrix of size (3,3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Create a *Diagonal* matrix
A diagonal matrix is a matrix with zero in all positions and different from 0 on the main diagonal.

In [31]:
d = np.diag(np.array([1, 2, 3, 4]))
print('The object type of d is:', type(d))
print('Diagonal matrix of size (4,4):\n',d)

The object type of d is: <class 'numpy.ndarray'>
Diagonal matrix of size (4,4):
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## Numerical computation with matrices

In [32]:
C=np.array([[0,0,1,0,1],[1,0,0,0,1],[0,0,0,1,1],[0,1,0,0,1],[1,1,1,1,0]])
print('The matrix C has the following element:\n',C)

The matrix C has the following element:
 [[0 0 1 0 1]
 [1 0 0 0 1]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [1 1 1 1 0]]


### Matrix transposition

In [33]:
print('The transpose matrix of the matrix C is:\n',C.T)

The transpose matrix of the matrix C is:
 [[0 1 0 0 1]
 [0 0 0 1 1]
 [1 0 0 0 1]
 [0 0 1 0 1]
 [1 1 1 1 0]]


### Product row by column of a matrix

In [34]:
print('The product row by column of matrix C \n\n{}\n\nwith itself is equals to: \n\n{}'.format(C,np.dot(C,C)))

The product row by column of matrix C 

[[0 0 1 0 1]
 [1 0 0 0 1]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [1 1 1 1 0]]

with itself is equals to: 

[[1 1 1 2 1]
 [1 1 2 1 1]
 [1 2 1 1 1]
 [2 1 1 1 1]
 [1 1 1 1 4]]


#### Alternative way to compute the product row by column of a matrix

In [35]:
print('Alternative way to compute the product row by column of matrix C \n\n{}\n\nwith itself: \n\n{}'.format(C,C@C))

Alternative way to compute the product row by column of matrix C 

[[0 0 1 0 1]
 [1 0 0 0 1]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [1 1 1 1 0]]

with itself: 

[[1 1 1 2 1]
 [1 1 2 1 1]
 [1 2 1 1 1]
 [2 1 1 1 1]
 [1 1 1 1 4]]


### Product element by element of a matrix

In [36]:
print('The product element by element of matrix C \n\n{}\n\nwith itself is equals to: \n\n{}'.format(C,C*C))

The product element by element of matrix C 

[[0 0 1 0 1]
 [1 0 0 0 1]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [1 1 1 1 0]]

with itself is equals to: 

[[0 0 1 0 1]
 [1 0 0 0 1]
 [0 0 0 1 1]
 [0 1 0 0 1]
 [1 1 1 1 0]]


## Comparing of computation time with and without loop with vectors

In [37]:
import time

### Computational time without loop

In [38]:
n = 1000000
a = np.arange(n)
print('Original vector a: {}'.format (a))

t1=time.process_time()
a = a + 1
t2a=time.process_time()-t1

print('Modified vector a1: {}'.format(a))
print('------------------------------------------------------------------------')
print('Computational time required to compute "a = a + 1" without loop: ',t2a)

Original vector a: [     0      1      2 ... 999997 999998 999999]
Modified vector a1: [      1       2       3 ...  999998  999999 1000000]
------------------------------------------------------------------------
Computational time required to compute "a = a + 1" without loop:  0.009650205999999883


### Computational time with loop

In [39]:
l = range(n)
b = np.empty(n)
print('Original vector b: {}\n'.format (b))

t1=time.process_time()
for i in l:
    b[i]=i+1
t2b=time.process_time()-t1

print('Modified vector b: {}'.format (b))
print('------------------------------------------------------------------------')
print('Computational time required to compute "b = b + 1" with loop: ',t2b)

Original vector b: [5.0233193e-310 6.5293026e-310 0.0000000e+000 ... 0.0000000e+000
 0.0000000e+000 0.0000000e+000]

Modified vector b: [1.00000e+00 2.00000e+00 3.00000e+00 ... 9.99998e+05 9.99999e+05
 1.00000e+06]
------------------------------------------------------------------------
Computational time required to compute "b = b + 1" with loop:  0.4188568720000001
