# Gaussian Elimination using Floating Point Arithmetic



---
This notebook highlight how to solve a linear system using the method **linalg.solve**() from the numpy package. In addition, the implementation of **Gaussian elimination**, **Backward substitution** and **Farward substitution** is provided and tested. Lastly, different example related to the application of Gaussian elimination and Backward substitution to a linear system, in Floating Point Arithmetic.

In [1]:
import numpy as np

## Solve a linear system using np.linalg.solve

### Create the matrix of coefficients **A** and the vector of coefficients **b** of size 3x3

In [2]:
A = np.random.rand(3,3)
b = np.array([1,2,3])
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =', b)

Matrix of coefficients A =
 [[0.67969713 0.83611592 0.38212299]
 [0.67168892 0.83666822 0.82048164]
 [0.70321879 0.55317056 0.14845559]]

Vector of known terms b = [1 2 3]


### Solve the linear system using *np.linalg.solve*()

In [3]:
x = np.linalg.solve(A,b)
print('The linear system solutions are: ', x)
print('The object type of the solutions vector is: ', type(x))

The linear system solutions are:  [10.24350443 -8.26402273  2.47878394]
The object type of the solutions vector is:  <class 'numpy.ndarray'>


### Check for the residuals (errors) between the exact solution and the computed one

In [4]:
print('The residual computed by A*x-b =', np.dot(A,x)-b)

The residual computed by A*x-b = [-1.22124533e-15 -8.88178420e-16 -4.44089210e-16]


## Gaussian Elimination, Backward Substitution and Forward Substitution implementation

### Gaussian Elimination
Implementation of Gaussian Elimination to use with square matrix.
* INPUT
  * **A**: Coefficient matrix A
  * **b**: Known terms vector
* OUTPUT
  * **U[:,0:n]**: The Upper Triangular matrix related to the input matrix A,
  * **U[:,n]**: The updated vector of known term

In [5]:
def gaussian_elimination(A, b):
  # Create the augumented matrix [A|b]
  U = np.hstack((A,b))

  # Retrive the number of rows and columns
  (m,n) = np.shape(U)

  for j in range(0,n):
    for i in range(j+1, m):

      # Compute M = U[i,j] / U[j,j]
      M = U[i,j] / U[j,j]

      # Put zero on all the element below the pivotal element
      U[i,j] = 0

      # Compute the row elimination
      for k in range(j+1, n):
        U[i,k] = U[i,k] - M * U[j,k]

  return U[:,0:n-1], U[:,n-1]

### Forward Substitution
Implementation of Forward Substitution used to solve a Lower Triangular System (implementation by row).
* INPUT
  * **A**: Coefficient matrix
  * **b**: Known terms vector
* OUTPUT
  * **solved**: Boolean values used to indicate if the system could be solved or not
  * **x**: A vector of solutions for the given system (if **solved** is True), or a sentence to indicate that the system could not be solved



In [6]:
def forward_substitution(A,b):
  solved = True

  # Check if the matrix is not singular
  # The product of the main diagonal MUST be =/= 0
  if(abs(np.prod(np.diag(A)))< 1.0e-18):
    x = 'Linear system without solution!'
    solved = False
  else:
    # Retrive the number of rows
    m = b.shape[0]

    # Create a vector to store the solutions
    x = np.zeros((m,1))

    # Compute the first solution of Lower Tr. System
    x[0]=b[0]/A[0,0]

    # Compute each solutions Xi and store it
    # np.dot compute the product row by columns up to the i-th row
    for i in range(1,m):
        x[i]=(b[i] - np.dot(A[i,0:i],x[0:i]))/A[i,i]
  return solved, x

### Backward Substitution
Implementation of Backward Substitution used to solve an Upper Triangular System (implementation by row).
* INPUT
  * **A**: Coefficient matrix
  * **b**: Known terms vector
* OUTPUT
  * **solved**: Boolean values used to indicate if the system could be solved or not
  * **x**: A vector of solutions for the given system (if **solved** is True), or a sentence to indicate that the system could not be solved

In [7]:
def backward_substitution(A,b):
  solved = True

  # Check if the matrix is not singular
  # The product of the main diagonal MUST be =/= 0
  if(abs(np.prod(np.diag(A)))< 1.0e-18):
    x = 'Linear system without solution!'
    solved = False
  else:
    # Retrive the number of rows
    m = b.shape[0]

    # Create a vector to store the solutions
    x = np.zeros((m,1))

    # Compute the first solution of Lower Tr. System
    x[m-1]=b[m-1]/A[m-1,m-1]

    # Compute each solutions Xi and store it
    # np.dot compute the product row by columns up to the i-th row
    for i in range(m-2, -1, -1):
        x[i]=(b[i] - np.dot(A[i,i:m],x[i:m]))/A[i,i]
  return solved, x

### Test of Forward substitution
To test our implementation we will create a Lower triangular system **L** with the exact solutions **xt** (x_true); then we will compute the vector of know terms **b** (b = Lxt). At this point, we will apply the **Forward substitution** on **L** and **b**, to find **x**. Lastly, we compare the xt and x, and we compute the absolute error.

In [8]:
# Define the size of linear system
n = 6

# Create the Lower traingual matrix of size n
L  = np.tril(np.random.rand(n,n))
print('Matrix of coefficients L =\n', L)

# Fix the exact solutions of the linear system to one
xt = np.ones((n,1))

# Compute the vector of known terms
b  = np.dot(L,xt)
print('\nVector of known terms b =\n', b)

# Computed the solutions using the Forward substitution
(solved, x)  = forward_substitution(L, b)

print('\n----------------------------------------')
if solved:
  print('\nThe exact solutions are xt =\n', xt)
  print('\nThe computed solutions are x =\n', x)
  print('\nThe absolute error with respect each solution is =\n', abs(x-xt))
else:
  print(x)

Matrix of coefficients L =
 [[0.77575602 0.         0.         0.         0.         0.        ]
 [0.58394942 0.56109285 0.         0.         0.         0.        ]
 [0.36645485 0.84571671 0.44761145 0.         0.         0.        ]
 [0.51988569 0.20194362 0.01276695 0.44083152 0.         0.        ]
 [0.88993832 0.05093963 0.58706302 0.32765585 0.33594017 0.        ]
 [0.03553036 0.19871051 0.94892973 0.24108113 0.95956805 0.2853365 ]]

Vector of known terms b =
 [[0.77575602]
 [1.14504227]
 [1.65978301]
 [1.17542777]
 [2.19153699]
 [2.66915628]]

----------------------------------------

The exact solutions are xt =
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

The computed solutions are x =
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

The absolute error with respect each solution is =
 [[0.00000000e+00]
 [2.22044605e-16]
 [4.44089210e-16]
 [0.00000000e+00]
 [6.66133815e-16]
 [0.00000000e+00]]


### Test of Gaussian elimination and Backward substitution

In [9]:
# Define the size of linear system
n = 6

# Create a coeffiecient matrix of size n
A  = np.random.rand(n,n)
print('Matrix of coefficients A =\n', A)

# Fix the exact solutions of the linear system to one
xt = np.ones((n,1))

# Compute the vector of known terms
b  = np.dot(A, xt)
print('\nVector of known terms b =\n', b)

# Compute the Gaussian elimination
(U, b_u) = gaussian_elimination(A, b)
print('\nUpper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

# Computed the solutions using the Backward substitution
(solved, x)  = backward_substitution(U, b_u)

print('\n----------------------------------------')
if solved:
  print('\nThe exact solutions are xt =\n', xt)
  print('\nThe computed solutions are x =\n', x)
  print('\nThe absolute error with respect each solution is =\n', abs(x-xt))
else:
  print(x)

Matrix of coefficients A =
 [[0.07441964 0.9169009  0.62588929 0.06442973 0.89545669 0.22481141]
 [0.76880415 0.30587453 0.46321211 0.90245509 0.41060704 0.55650443]
 [0.56682989 0.60976388 0.68344963 0.67179789 0.31691764 0.38032651]
 [0.58882401 0.49615821 0.07174855 0.42770203 0.59176855 0.67209192]
 [0.68835248 0.89455245 0.31274255 0.45338172 0.69990697 0.3041997 ]
 [0.03913208 0.7302265  0.95693328 0.7232111  0.52739711 0.45429038]]

Vector of known terms b =
 [[2.80190767]
 [3.40745737]
 [3.22908545]
 [2.84829328]
 [3.35313587]
 [3.43119044]]

Upper Triangular matrix of coefficients U =
 [[ 0.07441964  0.9169009   0.62588929  0.06442973  0.89545669  0.22481141]
 [ 0.         -9.16631843 -6.00263833  0.23685339 -8.84005299 -1.76594618]
 [ 0.          0.          0.09030217  0.01635755 -0.3563874  -0.10400475]
 [ 0.          0.          0.         -0.17438393 -1.7691134  -0.32808216]
 [ 0.          0.          0.          0.          0.22765675 -0.43551141]
 [ 0.          0.      

## Test of Gaussian elimination and Backward substitution with floating point arithmetic

In [10]:
par = 1e-17 # 10^(-17)

### Test n. 1



In [11]:
A = np.array( [[par,1.],[1., 2.]])
b = np.array([[1.],[3.]])

In [12]:
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =\n', b)

Matrix of coefficients A =
 [[1.e-17 1.e+00]
 [1.e+00 2.e+00]]

Vector of known terms b =
 [[1.]
 [3.]]


In [13]:
(U,b_u) = gaussian_elimination(A,b)
print('Upper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

Upper Triangular matrix of coefficients U =
 [[ 1.e-17  1.e+00]
 [ 0.e+00 -1.e+17]]

Vector of updated known terms b =
 [ 1.e+00 -1.e+17]


In [14]:
(solved, xg) = backward_substitution(U, b_u)

if solved:
  print('Solution after Gaussian Elimination and Backward substitution:\n', xg)
  print('\nSolution using np.linalg.solve(A,b):\n', np.linalg.solve(A, b))
else:
  print(xg)

Solution after Gaussian Elimination and Backward substitution:
 [[0.]
 [1.]]

Solution using np.linalg.solve(A,b):
 [[1.]
 [1.]]


### Test n. 2

In [15]:
A = np.array( [[10.,1./par],[1., 2.]])
b = np.array([[1./par],[3.]])

In [16]:
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =\n', b)

Matrix of coefficients A =
 [[1.e+01 1.e+17]
 [1.e+00 2.e+00]]

Vector of known terms b =
 [[1.e+17]
 [3.e+00]]


In [17]:
(U,b_u) = gaussian_elimination(A,b)
print('Upper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

Upper Triangular matrix of coefficients U =
 [[ 1.e+01  1.e+17]
 [ 0.e+00 -1.e+16]]

Vector of updated known terms b =
 [ 1.e+17 -1.e+16]


In [18]:
(solved, xg) = backward_substitution(U, b_u)

if solved:
  print('Solution after Gaussian Elimination and Backward substitution:\n', xg)
  print('\nSolution using np.linalg.solve(A,b):\n', np.linalg.solve(A, b))
else:
  print(xg)

Solution after Gaussian Elimination and Backward substitution:
 [[1.6]
 [1. ]]

Solution using np.linalg.solve(A,b):
 [[1.6]
 [1. ]]
