# Gaussian Elimination using Floating Point Arithmetic



---
This notebook highlight how to solve a linear system using the method ***linalg.solve***() from the numpy package. <br>In addition, an example will be used to show how there are no difference between row vectors and columns vectors. Then, an implementation of Gaussian Elimination method will be provided and used to solve linear system in Floating Point Arithmetic.

In [1]:
import numpy as np

## Solve a linear system using np.linalg.solve

### Create the matrix of coefficients **A** and the vector of coefficients **b** of size 3x3

In [2]:
A = np.random.rand(3,3)
b = np.array([1,2,3])
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =', b)

Matrix of coefficients A =
 [[0.73359333 0.5231925  0.70363143]
 [0.73687357 0.98571459 0.41112625]
 [0.56807274 0.81778324 0.79783696]]

Vector of known terms b = [1 2 3]


### Solve the linear system using *np.linalg.solve*()

In [3]:
x = np.linalg.solve(A,b)
print('The linear system solutions are: ', x)
print('The object type of the solutions vector is: ', type(x))

The linear system solutions are:  [-3.82646035  3.81634257  2.57291518]
The object type of the solutions vector is:  <class 'numpy.ndarray'>


### Check for the residuals (errors) between the exact solution and the computed one

In [4]:
print('The residual computed by A*x-b =', np.dot(A,x)-b)

The residual computed by A*x-b = [ 0.00000000e+00 -2.22044605e-16  0.00000000e+00]


## Gaussian Elimination, Backward Substitution and Forward Substitution implementation

### Gaussian Elimination
Implementation of Gaussian Elimination to use with square matrix.
* INPUT
  * **A**: Coefficient matrix A
  * **b**: Known terms vector
* OUTPUT
  * **U[:,0:n]**: The Upper Triangular matrix related to the input matrix A,
  * **U[:,n]**: The updated vector of known term

In [5]:
def gaussian_elimination(A, b):
  # Create the augumented matrix [A|b]
  U = np.hstack((A,b))

  # Retrive the number of rows and columns
  (m,n) = np.shape(U)

  for j in range(0,n):
    for i in range(j+1, m):

      #Calcolo m = matrix[i][j]/matrix[j][j]
      M = U[i,j] / U[j,j]

      #Azzero l'elemento sotto la diagonale principale
      U[i,j] = 0

      # Compute the row elimination
      for k in range(j+1, n):
        U[i,k] = U[i,k] - M * U[j,k]

  return U[:,0:n-1], U[:,n-1]

### Forward Substitution
Implementation of Forward Substitution used to solve a Lower Triangular System (implementation by row).
* INPUT
  * **A**: Coefficient matrix
  * **b**: Known terms vector
* OUTPUT
  * **solved**: Boolean values used to indicate if the system could be solved or not
  * **x**: A vector of solutions for the given system (if **solved** is True), or a sentence to indicate that the system could not be solved



In [6]:
def forward_substitution(A,b):
  solved = True

  # Check if the matrix is not singular
  # The product of the main diagonal MUST be =/= 0
  if(abs(np.prod(np.diag(A)))< 1.0e-18):
    x = 'Linear system without solution!'
    solved = False
  else:
    # Retrive the number of rows
    m = b.shape[0]

    # Create a vector to store the solutions
    x = np.zeros((m,1))

    # Compute the first solution of Lower Tr. System
    x[0]=b[0]/A[0,0]

    # Compute each solutions Xi and store it
    # np.dot compute the product row by columns up to the i-th row
    for i in range(1,m):
        x[i]=(b[i] - np.dot(A[i,0:i],x[0:i]))/A[i,i]
  return solved, x

### Backward Substitution
Implementation of Backward Substitution used to solve an Upper Triangular System (implementation by row).
* INPUT
  * **A**: Coefficient matrix
  * **b**: Known terms vector
* OUTPUT
  * **solved**: Boolean values used to indicate if the system could be solved or not
  * **x**: A vector of solutions for the given system (if **solved** is True), or a sentence to indicate that the system could not be solved

In [7]:
def backward_substitution(A,b):
  solved = True

  # Check if the matrix is not singular
  # The product of the main diagonal MUST be =/= 0
  if(abs(np.prod(np.diag(A)))< 1.0e-18):
    x = 'Linear system without solution!'
    solved = False
  else:
    # Retrive the number of rows
    m = b.shape[0]

    # Create a vector to store the solutions
    x = np.zeros((m,1))

    # Compute the first solution of Lower Tr. System
    x[m-1]=b[m-1]/A[m-1,m-1]

    # Compute each solutions Xi and store it
    # np.dot compute the product row by columns up to the i-th row
    for i in range(m-2, -1, -1):
        x[i]=(b[i] - np.dot(A[i,i:m],x[i:m]))/A[i,i]
  return solved, x

### Test of Forward substitution
To test our implementation we will create a Lower triangular system **L** with the exact solutions **xt** (x_true); then we will compute the vector of know terms **b** (b = Lxt). At this point, we will apply the **Forward substitution** on **L** and **b**, to find **x**. Lastly, we compare the xt and x, and we compute the absolute error.

In [8]:
# Define the size of linear system
n = 6

# Create the Lower traingual matrix of size n
L  = np.tril(np.random.rand(n,n))
print('Matrix of coefficients L =\n', L)

# Fix the exact solutions of the linear system to one
xt = np.ones((n,1))

# Compute the vector of known terms
b  = np.dot(L,xt)
print('\nVector of known terms b =\n', b)

# Computed the solutions using the Forward substitution
(solved, x)  = forward_substitution(L, b)

print('\n----------------------------------------')
if solved:
  print('\nThe exact solutions are xt =\n', xt)
  print('\nThe computed solutions are x =\n', x)
  print('\nThe absolute error with respect each solution is =\n', abs(x-xt))
else:
  print(x)

Matrix of coefficients L =
 [[0.13022779 0.         0.         0.         0.         0.        ]
 [0.38137482 0.48115153 0.         0.         0.         0.        ]
 [0.77966617 0.64289129 0.6629755  0.         0.         0.        ]
 [0.16564415 0.80922068 0.65669772 0.84215741 0.         0.        ]
 [0.45761416 0.75900911 0.97637413 0.57901641 0.67407443 0.        ]
 [0.54429385 0.62043978 0.17497646 0.05604573 0.35350086 0.98236318]]

Vector of known terms b =
 [[0.13022779]
 [0.86252634]
 [2.08553296]
 [2.47371997]
 [3.44608824]
 [2.73161986]]

----------------------------------------

The exact solutions are xt =
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

The computed solutions are x =
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

The absolute error with respect each solution is =
 [[0.00000000e+00]
 [0.00000000e+00]
 [4.44089210e-16]
 [4.44089210e-16]
 [7.77156117e-16]
 [2.22044605e-16]]


### Test of Gaussian elimination and Backward substitution

In [9]:
# Define the size of linear system
n = 6

# Create a coeffiecient matrix of size n
A  = np.random.rand(n,n)
print('Matrix of coefficients A =\n', A)

# Fix the exact solutions of the linear system to one
xt = np.ones((n,1))

# Compute the vector of known terms
b  = np.dot(A, xt)
print('\nVector of known terms b =\n', b)

# Compute the Gaussian elimination
(U, b_u) = gaussian_elimination(A, b)
print('\nUpper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

# Computed the solutions using the Backward substitution
(solved, x)  = backward_substitution(U, b_u)

print('\n----------------------------------------')
if solved:
  print('\nThe exact solutions are xt =\n', xt)
  print('\nThe computed solutions are x =\n', x)
  print('\nThe absolute error with respect each solution is =\n', abs(x-xt))
else:
  print(x)

Matrix of coefficients A =
 [[0.85340509 0.84686595 0.65093755 0.00638201 0.22382099 0.40801402]
 [0.58939135 0.7072033  0.22388221 0.57111405 0.67384024 0.24245167]
 [0.55916044 0.3677256  0.75177205 0.04117998 0.22122002 0.56108508]
 [0.60196349 0.79660369 0.3930268  0.22257915 0.52164616 0.87514721]
 [0.51805142 0.35425816 0.06627205 0.29112164 0.31739921 0.17288246]
 [0.78154312 0.14053668 0.69925327 0.53831098 0.66159811 0.00331022]]

Vector of known terms b =
 [[2.98942561]
 [3.00788283]
 [2.50214317]
 [3.4109665 ]
 [1.71998494]
 [2.82455239]]

Upper Triangular matrix of coefficients U =
 [[ 8.53405088e-01  8.46865952e-01  6.50937549e-01  6.38200821e-03
   2.23820994e-01  4.08014019e-01]
 [ 0.00000000e+00  1.22328104e-01 -2.25677991e-01  5.66706415e-01
   5.19261651e-01 -3.93370593e-02]
 [ 0.00000000e+00  0.00000000e+00 -1.99952192e-02  9.04005163e-01
   8.68990812e-01  2.33567845e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.29247887e+01
   1.26198462e+01  4.17294926

## Test of Gaussian elimination and Backward substitution with floating point arithmetic

In [10]:
par = 1e-17 # 10^(-17)

### Test n. 1



In [11]:
A = np.array( [[par,1.],[1., 2.]])
b = np.array([[1.],[3.]])

In [12]:
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =\n', b)

Matrix of coefficients A =
 [[1.e-17 1.e+00]
 [1.e+00 2.e+00]]

Vector of known terms b =
 [[1.]
 [3.]]


In [13]:
(U,b_u) = gaussian_elimination(A,b)
print('Upper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

Upper Triangular matrix of coefficients U =
 [[ 1.e-17  1.e+00]
 [ 0.e+00 -1.e+17]]

Vector of updated known terms b =
 [ 1.e+00 -1.e+17]


In [14]:
(solved, xg) = backward_substitution(U, b_u)

if solved:
  print('Solution after Gaussian Elimination and Backward substitution:\n', xg)
  print('\nSolution using np.linalg.solve(A,b):\n', np.linalg.solve(A, b))
else:
  print(xg)

Solution after Gaussian Elimination and Backward substitution:
 [[0.]
 [1.]]

Solution using np.linalg.solve(A,b):
 [[1.]
 [1.]]


### Test n.2

In [15]:
A = np.array( [[10.,1./par],[1., 2.]])
b = np.array([[1./par],[3.]])

In [16]:
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =\n', b)

Matrix of coefficients A =
 [[1.e+01 1.e+17]
 [1.e+00 2.e+00]]

Vector of known terms b =
 [[1.e+17]
 [3.e+00]]


In [17]:
(U,b_u) = gaussian_elimination(A,b)
print('Upper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

Upper Triangular matrix of coefficients U =
 [[ 1.e+01  1.e+17]
 [ 0.e+00 -1.e+16]]

Vector of updated known terms b =
 [ 1.e+17 -1.e+16]


In [18]:
(solved, xg) = backward_substitution(U, b_u)

if solved:
  print('Solution after Gaussian Elimination and Backward substitution:\n', xg)
  print('\nSolution using np.linalg.solve(A,b):\n', np.linalg.solve(A, b))
else:
  print(xg)

Solution after Gaussian Elimination and Backward substitution:
 [[1.6]
 [1. ]]

Solution using np.linalg.solve(A,b):
 [[1.6]
 [1. ]]
