# Gaussian Elimination using Floating Point Arithmetic



---
This notebook highlight how to solve a linear system using the method **linalg.solve**() from the numpy package. In addition, the implementation of **Gaussian elimination**, **Backward substitution** and **Farward substitution** is provided and tested. Lastly, different example related to the application of Gaussian elimination and Backward substitution to a linear system, in Floating Point Arithmetic.

In [1]:
import numpy as np

## Solve a linear system using np.linalg.solve

### Create the matrix of coefficients **A** and the vector of coefficients **b** of size 3x3

In [2]:
A = np.random.rand(3,3)
b = np.array([1,2,3])
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =', b)

Matrix of coefficients A =
 [[0.41228285 0.83103959 0.03999559]
 [0.06140168 0.57610425 0.29251998]
 [0.11387395 0.976891   0.36447391]]

Vector of known terms b = [1 2 3]


### Solve the linear system using *np.linalg.solve*()

In [3]:
x = np.linalg.solve(A,b)
print('The linear system solutions are: ', x)
print('The object type of the solutions vector is: ', type(x))

The linear system solutions are:  [-2.5344551   2.32653037  2.78714557]
The object type of the solutions vector is:  <class 'numpy.ndarray'>


### Check for the residuals (errors) between the exact solution and the computed one

In [4]:
print('The residual computed by A*x-b =', np.dot(A,x)-b)

The residual computed by A*x-b = [-1.11022302e-16  0.00000000e+00 -4.44089210e-16]


## Gaussian Elimination, Backward Substitution and Forward Substitution implementation

### Gaussian Elimination
Implementation of Gaussian Elimination to use with square matrix.
* INPUT
  * **A**: Coefficient matrix A
  * **b**: Known terms vector
* OUTPUT
  * **U[:,0:n]**: The Upper Triangular matrix related to the input matrix A,
  * **U[:,n]**: The updated vector of known term

In [5]:
def gaussian_elimination(A, b):
  # Create the augumented matrix [A|b]
  U = np.hstack((A,b))

  # Retrive the number of rows and columns
  (m,n) = np.shape(U)

  for j in range(0,n):
    for i in range(j+1, m):

      #Calcolo m = matrix[i][j]/matrix[j][j]
      M = U[i,j] / U[j,j]

      #Azzero l'elemento sotto la diagonale principale
      U[i,j] = 0

      # Compute the row elimination
      for k in range(j+1, n):
        U[i,k] = U[i,k] - M * U[j,k]

  return U[:,0:n-1], U[:,n-1]

### Forward Substitution
Implementation of Forward Substitution used to solve a Lower Triangular System (implementation by row).
* INPUT
  * **A**: Coefficient matrix
  * **b**: Known terms vector
* OUTPUT
  * **solved**: Boolean values used to indicate if the system could be solved or not
  * **x**: A vector of solutions for the given system (if **solved** is True), or a sentence to indicate that the system could not be solved



In [6]:
def forward_substitution(A,b):
  solved = True

  # Check if the matrix is not singular
  # The product of the main diagonal MUST be =/= 0
  if(abs(np.prod(np.diag(A)))< 1.0e-18):
    x = 'Linear system without solution!'
    solved = False
  else:
    # Retrive the number of rows
    m = b.shape[0]

    # Create a vector to store the solutions
    x = np.zeros((m,1))

    # Compute the first solution of Lower Tr. System
    x[0]=b[0]/A[0,0]

    # Compute each solutions Xi and store it
    # np.dot compute the product row by columns up to the i-th row
    for i in range(1,m):
        x[i]=(b[i] - np.dot(A[i,0:i],x[0:i]))/A[i,i]
  return solved, x

### Backward Substitution
Implementation of Backward Substitution used to solve an Upper Triangular System (implementation by row).
* INPUT
  * **A**: Coefficient matrix
  * **b**: Known terms vector
* OUTPUT
  * **solved**: Boolean values used to indicate if the system could be solved or not
  * **x**: A vector of solutions for the given system (if **solved** is True), or a sentence to indicate that the system could not be solved

In [7]:
def backward_substitution(A,b):
  solved = True

  # Check if the matrix is not singular
  # The product of the main diagonal MUST be =/= 0
  if(abs(np.prod(np.diag(A)))< 1.0e-18):
    x = 'Linear system without solution!'
    solved = False
  else:
    # Retrive the number of rows
    m = b.shape[0]

    # Create a vector to store the solutions
    x = np.zeros((m,1))

    # Compute the first solution of Lower Tr. System
    x[m-1]=b[m-1]/A[m-1,m-1]

    # Compute each solutions Xi and store it
    # np.dot compute the product row by columns up to the i-th row
    for i in range(m-2, -1, -1):
        x[i]=(b[i] - np.dot(A[i,i:m],x[i:m]))/A[i,i]
  return solved, x

### Test of Forward substitution
To test our implementation we will create a Lower triangular system **L** with the exact solutions **xt** (x_true); then we will compute the vector of know terms **b** (b = Lxt). At this point, we will apply the **Forward substitution** on **L** and **b**, to find **x**. Lastly, we compare the xt and x, and we compute the absolute error.

In [8]:
# Define the size of linear system
n = 6

# Create the Lower traingual matrix of size n
L  = np.tril(np.random.rand(n,n))
print('Matrix of coefficients L =\n', L)

# Fix the exact solutions of the linear system to one
xt = np.ones((n,1))

# Compute the vector of known terms
b  = np.dot(L,xt)
print('\nVector of known terms b =\n', b)

# Computed the solutions using the Forward substitution
(solved, x)  = forward_substitution(L, b)

print('\n----------------------------------------')
if solved:
  print('\nThe exact solutions are xt =\n', xt)
  print('\nThe computed solutions are x =\n', x)
  print('\nThe absolute error with respect each solution is =\n', abs(x-xt))
else:
  print(x)

Matrix of coefficients L =
 [[0.49531488 0.         0.         0.         0.         0.        ]
 [0.62141357 0.27619937 0.         0.         0.         0.        ]
 [0.60662369 0.97847926 0.44532596 0.         0.         0.        ]
 [0.63592408 0.99177663 0.78205115 0.50641667 0.         0.        ]
 [0.06579304 0.9213664  0.37012749 0.77528573 0.22929773 0.        ]
 [0.66205518 0.88634067 0.49961392 0.13099103 0.62150154 0.1973195 ]]

Vector of known terms b =
 [[0.49531488]
 [0.89761293]
 [2.03042891]
 [2.91616852]
 [2.36187038]
 [2.99782185]]

----------------------------------------

The exact solutions are xt =
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

The computed solutions are x =
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

The absolute error with respect each solution is =
 [[0.0000000e+00]
 [0.0000000e+00]
 [4.4408921e-16]
 [4.4408921e-16]
 [4.4408921e-16]
 [0.0000000e+00]]


### Test of Gaussian elimination and Backward substitution

In [9]:
# Define the size of linear system
n = 6

# Create a coeffiecient matrix of size n
A  = np.random.rand(n,n)
print('Matrix of coefficients A =\n', A)

# Fix the exact solutions of the linear system to one
xt = np.ones((n,1))

# Compute the vector of known terms
b  = np.dot(A, xt)
print('\nVector of known terms b =\n', b)

# Compute the Gaussian elimination
(U, b_u) = gaussian_elimination(A, b)
print('\nUpper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

# Computed the solutions using the Backward substitution
(solved, x)  = backward_substitution(U, b_u)

print('\n----------------------------------------')
if solved:
  print('\nThe exact solutions are xt =\n', xt)
  print('\nThe computed solutions are x =\n', x)
  print('\nThe absolute error with respect each solution is =\n', abs(x-xt))
else:
  print(x)

Matrix of coefficients A =
 [[0.6307402  0.36111469 0.52781332 0.95929689 0.2886837  0.7923878 ]
 [0.74998396 0.43907808 0.69232842 0.86095286 0.22011563 0.98862287]
 [0.29041836 0.46192684 0.54363181 0.95019526 0.56708741 0.49840951]
 [0.21412966 0.76642778 0.41499708 0.09854431 0.77979002 0.35358069]
 [0.62966736 0.10526023 0.87551058 0.43974065 0.53073531 0.37112635]
 [0.72115163 0.23464935 0.85851516 0.2936605  0.97222565 0.31647973]]

Vector of known terms b =
 [[3.5600366 ]
 [3.95108183]
 [3.31166918]
 [2.62746954]
 [2.95204048]
 [3.39668202]]

Upper Triangular matrix of coefficients U =
 [[ 0.6307402   0.36111469  0.52781332  0.95929689  0.2886837   0.7923878 ]
 [ 0.          0.00969333  0.06473004 -0.27970265 -0.12314478  0.04643124]
 [ 0.          0.         -1.6737174   9.03967048  4.19018891 -1.28263117]
 [ 0.          0.          0.         -3.5963883  -1.31215841  0.11466598]
 [ 0.          0.          0.          0.          0.97025825 -0.66842426]
 [ 0.          0.      

## Test of Gaussian elimination and Backward substitution with floating point arithmetic

In [10]:
par = 1e-17 # 10^(-17)

### Test n. 1



In [11]:
A = np.array( [[par,1.],[1., 2.]])
b = np.array([[1.],[3.]])

In [12]:
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =\n', b)

Matrix of coefficients A =
 [[1.e-17 1.e+00]
 [1.e+00 2.e+00]]

Vector of known terms b =
 [[1.]
 [3.]]


In [13]:
(U,b_u) = gaussian_elimination(A,b)
print('Upper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

Upper Triangular matrix of coefficients U =
 [[ 1.e-17  1.e+00]
 [ 0.e+00 -1.e+17]]

Vector of updated known terms b =
 [ 1.e+00 -1.e+17]


In [14]:
(solved, xg) = backward_substitution(U, b_u)

if solved:
  print('Solution after Gaussian Elimination and Backward substitution:\n', xg)
  print('\nSolution using np.linalg.solve(A,b):\n', np.linalg.solve(A, b))
else:
  print(xg)

Solution after Gaussian Elimination and Backward substitution:
 [[0.]
 [1.]]

Solution using np.linalg.solve(A,b):
 [[1.]
 [1.]]


### Test n.2

In [15]:
A = np.array( [[10.,1./par],[1., 2.]])
b = np.array([[1./par],[3.]])

In [16]:
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =\n', b)

Matrix of coefficients A =
 [[1.e+01 1.e+17]
 [1.e+00 2.e+00]]

Vector of known terms b =
 [[1.e+17]
 [3.e+00]]


In [17]:
(U,b_u) = gaussian_elimination(A,b)
print('Upper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

Upper Triangular matrix of coefficients U =
 [[ 1.e+01  1.e+17]
 [ 0.e+00 -1.e+16]]

Vector of updated known terms b =
 [ 1.e+17 -1.e+16]


In [18]:
(solved, xg) = backward_substitution(U, b_u)

if solved:
  print('Solution after Gaussian Elimination and Backward substitution:\n', xg)
  print('\nSolution using np.linalg.solve(A,b):\n', np.linalg.solve(A, b))
else:
  print(xg)

Solution after Gaussian Elimination and Backward substitution:
 [[1.6]
 [1. ]]

Solution using np.linalg.solve(A,b):
 [[1.6]
 [1. ]]
