# Gaussian Elimination using Floating Point Arithmetic



---
This notebook highlight how to solve a linear system using the method **linalg.solve**() from the numpy package. In addition, the implementation of **Gaussian elimination**, **Backward substitution** and **Farward substitution** is provided and tested. Lastly, different example related to the application of Gaussian elimination and Backward substitution to a linear system, in Floating Point Arithmetic.

In [19]:
import numpy as np

## Solve a linear system using np.linalg.solve

### Create the matrix of coefficients **A** and the vector of coefficients **b** of size 3x3

In [20]:
A = np.random.rand(3,3)
b = np.array([1,2,3])
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =', b)

Matrix of coefficients A =
 [[0.97048533 0.04573011 0.83571434]
 [0.67170073 0.431075   0.6904319 ]
 [0.47884456 0.6180529  0.07823235]]

Vector of known terms b = [1 2 3]


### Solve the linear system using *np.linalg.solve*()

In [21]:
x = np.linalg.solve(A,b)
print('The linear system solutions are: ', x)
print('The object type of the solutions vector is: ', type(x))

The linear system solutions are:  [ 1.81814665  3.5859483  -1.11099022]
The object type of the solutions vector is:  <class 'numpy.ndarray'>


### Check for the residuals (errors) between the exact solution and the computed one

In [22]:
print('The residual computed by A*x-b =', np.dot(A,x)-b)

The residual computed by A*x-b = [-2.22044605e-16  0.00000000e+00  0.00000000e+00]


## Gaussian Elimination, Backward Substitution and Forward Substitution implementation

### Gaussian Elimination
Implementation of Gaussian Elimination to use with square matrix.
* INPUT
  * **A**: Coefficient matrix A
  * **b**: Known terms vector
* OUTPUT
  * **U[:,0:n]**: The Upper Triangular matrix related to the input matrix A,
  * **U[:,n]**: The updated vector of known term

In [23]:
def gaussian_elimination(A, b):
  # Create the augumented matrix [A|b]
  U = np.hstack((A,b))

  # Retrive the number of rows and columns
  (m,n) = np.shape(U)

  for j in range(0,n):
    for i in range(j+1, m):

      #Calcolo m = matrix[i][j]/matrix[j][j]
      M = U[i,j] / U[j,j]

      #Azzero l'elemento sotto la diagonale principale
      U[i,j] = 0

      # Compute the row elimination
      for k in range(j+1, n):
        U[i,k] = U[i,k] - M * U[j,k]

  return U[:,0:n-1], U[:,n-1]

### Forward Substitution
Implementation of Forward Substitution used to solve a Lower Triangular System (implementation by row).
* INPUT
  * **A**: Coefficient matrix
  * **b**: Known terms vector
* OUTPUT
  * **solved**: Boolean values used to indicate if the system could be solved or not
  * **x**: A vector of solutions for the given system (if **solved** is True), or a sentence to indicate that the system could not be solved



In [24]:
def forward_substitution(A,b):
  solved = True

  # Check if the matrix is not singular
  # The product of the main diagonal MUST be =/= 0
  if(abs(np.prod(np.diag(A)))< 1.0e-18):
    x = 'Linear system without solution!'
    solved = False
  else:
    # Retrive the number of rows
    m = b.shape[0]

    # Create a vector to store the solutions
    x = np.zeros((m,1))

    # Compute the first solution of Lower Tr. System
    x[0]=b[0]/A[0,0]

    # Compute each solutions Xi and store it
    # np.dot compute the product row by columns up to the i-th row
    for i in range(1,m):
        x[i]=(b[i] - np.dot(A[i,0:i],x[0:i]))/A[i,i]
  return solved, x

### Backward Substitution
Implementation of Backward Substitution used to solve an Upper Triangular System (implementation by row).
* INPUT
  * **A**: Coefficient matrix
  * **b**: Known terms vector
* OUTPUT
  * **solved**: Boolean values used to indicate if the system could be solved or not
  * **x**: A vector of solutions for the given system (if **solved** is True), or a sentence to indicate that the system could not be solved

In [25]:
def backward_substitution(A,b):
  solved = True

  # Check if the matrix is not singular
  # The product of the main diagonal MUST be =/= 0
  if(abs(np.prod(np.diag(A)))< 1.0e-18):
    x = 'Linear system without solution!'
    solved = False
  else:
    # Retrive the number of rows
    m = b.shape[0]

    # Create a vector to store the solutions
    x = np.zeros((m,1))

    # Compute the first solution of Lower Tr. System
    x[m-1]=b[m-1]/A[m-1,m-1]

    # Compute each solutions Xi and store it
    # np.dot compute the product row by columns up to the i-th row
    for i in range(m-2, -1, -1):
        x[i]=(b[i] - np.dot(A[i,i:m],x[i:m]))/A[i,i]
  return solved, x

### Test of Forward substitution
To test our implementation we will create a Lower triangular system **L** with the exact solutions **xt** (x_true); then we will compute the vector of know terms **b** (b = Lxt). At this point, we will apply the **Forward substitution** on **L** and **b**, to find **x**. Lastly, we compare the xt and x, and we compute the absolute error.

In [26]:
# Define the size of linear system
n = 6

# Create the Lower traingual matrix of size n
L  = np.tril(np.random.rand(n,n))
print('Matrix of coefficients L =\n', L)

# Fix the exact solutions of the linear system to one
xt = np.ones((n,1))

# Compute the vector of known terms
b  = np.dot(L,xt)
print('\nVector of known terms b =\n', b)

# Computed the solutions using the Forward substitution
(solved, x)  = forward_substitution(L, b)

print('\n----------------------------------------')
if solved:
  print('\nThe exact solutions are xt =\n', xt)
  print('\nThe computed solutions are x =\n', x)
  print('\nThe absolute error with respect each solution is =\n', abs(x-xt))
else:
  print(x)

Matrix of coefficients L =
 [[0.81228482 0.         0.         0.         0.         0.        ]
 [0.83420717 0.42998147 0.         0.         0.         0.        ]
 [0.78256436 0.68567662 0.36222336 0.         0.         0.        ]
 [0.26067299 0.93980765 0.14082403 0.49668331 0.         0.        ]
 [0.68547514 0.49308565 0.90482384 0.83811156 0.85771567 0.        ]
 [0.5590827  0.24371741 0.60533621 0.3509194  0.49819738 0.16681807]]

Vector of known terms b =
 [[0.81228482]
 [1.26418864]
 [1.83046434]
 [1.83798798]
 [3.77921186]
 [2.42407117]]

----------------------------------------

The exact solutions are xt =
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

The computed solutions are x =
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

The absolute error with respect each solution is =
 [[0.00000000e+00]
 [2.22044605e-16]
 [6.66133815e-16]
 [4.44089210e-16]
 [1.33226763e-15]
 [1.33226763e-15]]


### Test of Gaussian elimination and Backward substitution

In [27]:
# Define the size of linear system
n = 6

# Create a coeffiecient matrix of size n
A  = np.random.rand(n,n)
print('Matrix of coefficients A =\n', A)

# Fix the exact solutions of the linear system to one
xt = np.ones((n,1))

# Compute the vector of known terms
b  = np.dot(A, xt)
print('\nVector of known terms b =\n', b)

# Compute the Gaussian elimination
(U, b_u) = gaussian_elimination(A, b)
print('\nUpper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

# Computed the solutions using the Backward substitution
(solved, x)  = backward_substitution(U, b_u)

print('\n----------------------------------------')
if solved:
  print('\nThe exact solutions are xt =\n', xt)
  print('\nThe computed solutions are x =\n', x)
  print('\nThe absolute error with respect each solution is =\n', abs(x-xt))
else:
  print(x)

Matrix of coefficients A =
 [[0.75676663 0.26164061 0.62071834 0.34692251 0.39990576 0.45916823]
 [0.18587485 0.17696444 0.58652163 0.46734006 0.9061148  0.92588088]
 [0.21769591 0.35865972 0.19994513 0.37931297 0.30295511 0.82326845]
 [0.05554716 0.52146792 0.50380405 0.95204635 0.17965161 0.66068869]
 [0.18176076 0.96342915 0.51405058 0.01766975 0.36722329 0.58976875]
 [0.52318985 0.10395623 0.90417354 0.76219379 0.98487509 0.75453518]]

Vector of known terms b =
 [[2.84512208]
 [3.24869666]
 [2.28183729]
 [2.87320578]
 [2.63390229]
 [4.03292368]]

Upper Triangular matrix of coefficients U =
 [[ 0.75676663  0.26164061  0.62071834  0.34692251  0.39990576  0.45916823]
 [ 0.          0.11270102  0.43406257  0.38212995  0.80789109  0.81310129]
 [ 0.          0.         -1.0700952  -0.68137742 -1.8435831  -1.35341897]
 [ 0.          0.          0.          0.16354443 -0.90691938 -1.12963516]
 [ 0.          0.          0.          0.         -7.17624721 -9.98778304]
 [ 0.          0.      

## Test of Gaussian elimination and Backward substitution with floating point arithmetic

In [28]:
par = 1e-17 # 10^(-17)

### Test n. 1



In [29]:
A = np.array( [[par,1.],[1., 2.]])
b = np.array([[1.],[3.]])

In [30]:
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =\n', b)

Matrix of coefficients A =
 [[1.e-17 1.e+00]
 [1.e+00 2.e+00]]

Vector of known terms b =
 [[1.]
 [3.]]


In [31]:
(U,b_u) = gaussian_elimination(A,b)
print('Upper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

Upper Triangular matrix of coefficients U =
 [[ 1.e-17  1.e+00]
 [ 0.e+00 -1.e+17]]

Vector of updated known terms b =
 [ 1.e+00 -1.e+17]


In [32]:
(solved, xg) = backward_substitution(U, b_u)

if solved:
  print('Solution after Gaussian Elimination and Backward substitution:\n', xg)
  print('\nSolution using np.linalg.solve(A,b):\n', np.linalg.solve(A, b))
else:
  print(xg)

Solution after Gaussian Elimination and Backward substitution:
 [[0.]
 [1.]]

Solution using np.linalg.solve(A,b):
 [[1.]
 [1.]]


### Test n.2

In [33]:
A = np.array( [[10.,1./par],[1., 2.]])
b = np.array([[1./par],[3.]])

In [34]:
print('Matrix of coefficients A =\n', A)
print('\nVector of known terms b =\n', b)

Matrix of coefficients A =
 [[1.e+01 1.e+17]
 [1.e+00 2.e+00]]

Vector of known terms b =
 [[1.e+17]
 [3.e+00]]


In [35]:
(U,b_u) = gaussian_elimination(A,b)
print('Upper Triangular matrix of coefficients U =\n', U)
print('\nVector of updated known terms b =\n', b_u)

Upper Triangular matrix of coefficients U =
 [[ 1.e+01  1.e+17]
 [ 0.e+00 -1.e+16]]

Vector of updated known terms b =
 [ 1.e+17 -1.e+16]


In [36]:
(solved, xg) = backward_substitution(U, b_u)

if solved:
  print('Solution after Gaussian Elimination and Backward substitution:\n', xg)
  print('\nSolution using np.linalg.solve(A,b):\n', np.linalg.solve(A, b))
else:
  print(xg)

Solution after Gaussian Elimination and Backward substitution:
 [[1.6]
 [1. ]]

Solution using np.linalg.solve(A,b):
 [[1.6]
 [1. ]]
